#include<iostream.h>
#include<conio.h>

void main()
{
	clrscr;
   cout<<"jjjjjjjjj       mmmmmmmmmm           mm         mm"<<endl;
   cout<<"jjjjjjjjj       mmmmmmmmmm           mm mm   mm mm"<<endl;
   cout<<"       jj       mm                   mm   mm    mm"<<endl;
   cout<<"       jj       mm                   mm         mm"<<endl;
   cout<<"       jj       mmmmmm               mm         mm"<<endl;
   cout<<"       jj       mm                   mm         mm"<<endl;
   cout<<"jjjjjjjjj       mm                   mm         mm"<<endl;
   cout<<"jjjjjjjjj       mm                   mm         mm"<<endl;
getch();
}

//Latihan no 2
